# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66b568339907c768a6613fe00b4253965f5475a6232d750a15942ae4b6c8170088389f681cc7c661ca58c160c39a80e94458fcdc68cae25f45b067bf555caef0

test:
  secret_key_base: b54af315defcbdcfd7d0acb64ff45baf1265da3c77999273d8574517fc8586ba1c3095ac2148476528db51aa4b341888e7742e2708906cecb37b307e2d8995d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
